"""empty message

Revision ID: 88010898d0ca
Revises: 
Create Date: 2020-12-27 18:29:27.371649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88010898d0ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dessert', ['title'])
    op.create_unique_constraint(None, 'drink', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drink', type_='unique')
    op.drop_constraint(None, 'dessert', type_='unique')
    # ### end Alembic commands ###
